### PR TITLE
Switch to using multiple getKey's instead of the getKeySlice

### PR DESCRIPTION
**Pull request by emilssolmanis**

### CODE REVIEW

**Comment by Dalamar42** [comment]
LGTM

**Comment by Dalamar42** [comment]
Agree on timeout

**Comment by Dalamar42** [comment]
Also it doesn't apply here but for future things, there is something in Futures to convert a collection of listenables returning single values to a listenable returning a collection of the same return type

**Comment by emilssolmanis** [comment]
@Dalamar42 err, yes, it's `Futures.allAsList` and it's used on line 169.

**Pull request merged**
